src/RouteAttributesServiceProvider.php

In #8 's pull request I noticed there was a missing config field that wasn't actually registering routes at an application level. This PR fixes that but does not add the route root namespace to avoid merging two separate issues.

Add missing config prefix to RouteAttributesServiceProvider.php

---

config/route-attributes.php
src/RouteAttributesServiceProvider.php
src/RouteRegistrar.php
tests/RouteRegistrarTest.php
tests/TestCase.php
tests/TestClasses/Middleware/AnotherTestMiddleware.php

Middlewares like \Illuminate\Routing\Middleware\SubstituteBindings::class, are used for all routes. With current version of route attributes you cannot apply a middleware to all routes.
I added a field to route-attributes.php named `middlewares`, with this field you can add middlewares that will be applied to all routes.
This also fixes #13 , because SubstituteBindings middleware is comes default in config file.

Applying selected middlewares to all routes feature implemented.

---

src/RouteAttributesServiceProvider.php
tests/AttributeTests/MiddlewareAttributeTest.php
tests/AttributeTests/RouteAttributeTest.php
tests/RouteRegistrarTest.php
tests/TestCase.php
tests/TestClasses/Controllers/MiddlewareTestController.php
tests/TestClasses/Controllers/RouteAttribute/RouteMiddlewareTestController.php
tests/TestClasses/Middleware/AnotherTestMiddleware.php
tests/TestClasses/Middleware/OtherTestMiddleware.php
tests/TestClasses/Middleware/TestMiddleware.php

This PR aims to fix the following error when running integration tests:
`DirectoryNotFoundException: src/../tests/TestClasses" directory does not exist.`
This happens because the package tries to use the `TestClasses` directory even though is doesn't exists when running tests in a real Laravel application.

Add new check to make sure TestClasses directory exists when running tests

---

src/RouteRegistrar.php
tests/AttributeTests/PrefixAttributeTest.php
tests/TestClasses/Controllers/PrefixTestController.php

This PR aims to fix an edge case with the current implementation of `#[Prefix]`, currently the routes are registered first and then the prefix is applied, which leads to an error when registering nested root routes e.g. `#[Get("/")]`.
The new approach proposed in this PR follows the implementation described in the Laravel official docs.
https://laravel.com/docs/8.x/routing#route-group-prefixes
Feel free to ask me to change anything or to propose another way of fixing the issue.
Also, I would like to point out something about how the tests verify the routes were correctly registered.
https://github.com/spatie/laravel-route-attributes/blob/master/tests/TestCase.php#L63
Even though this approach works for the majority of cases, it's not how Laravel matches routes internally, which could lead …

Change approach to handle routes with prefix

---

src/RouteRegistrar.php

For example:
If config file (route-attribute.php) has:
// This middleware will be applied to all routes.
'middleware' => [
'web',
],
And Controller has:
#[Get('/dashboard'), middleware: ['auth'])
It will always redirect to /login, because auth middleware was registered before web middleware

Global middleware from config file should be registered first

---

README.md
src/Attributes/Any.php
src/Attributes/Delete.php
src/Attributes/Get.php
src/Attributes/Options.php
src/Attributes/Patch.php
src/Attributes/Post.php
src/Attributes/Put.php
src/Attributes/Route.php
src/RouteRegistrar.php
tests/AttributeTests/DomainAttributeTest.php
tests/AttributeTests/PrefixAttributeTest.php
tests/AttributeTests/RouteAttributeTest.php
tests/TestCase.php
tests/TestClasses/Controllers/RouteAttribute/RouteMultiVerbTestController.php

This PR adds support for registering routes with multiple verbs, which comes in handy at times. Essentially, I just widened the `method` parameter of the `Route` attribute to accept an array of verbs - everything else is just a consequence of that modification. 
The most complex part is uppercasing common HTTP methods, as they are case-sensitive per [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.1), so to not break existing implementations and keep the convenience of `Route('get')`, all methods [exposed by the Laravel router](https://github.com/laravel/framework/blob/81ef9850cc388f2f92b868fb35ffb76f0c9a0f46/src/Illuminate/Routing/Router.php#L122) will be converted to uppercase.
This PR does not contain any breaking changes.

Added possibility to register multiple verbs for a route

---

README.md
src/Attributes/DomainFromConfig.php
src/ClassRouteAttributes.php
src/RouteRegistrar.php
tests/AttributeTests/Domain1AttributeTest.php
tests/AttributeTests/DomainFromConfigAttributeTest.php
tests/TestCase.php
tests/TestClasses/Controllers/Domain1TestController.php
tests/TestClasses/Controllers/Domain2TestController.php
tests/TestClasses/Controllers/DomainFromConfigTestController.php

This PR adds in the functionality in order to be able to pull a domain from a specified configuration file. This is particularly useful when you have different subdomain urls between local and production. 
Further details are available in the updated readme.

Add additional functionality to get domain from a config file.

---

src/ClassRouteAttributes.php

This PR will allow developers to inherit from the provided attributes and still keep the functionality, e.g.:
```php
<?php
namespace App\Attributes;
use Attribute;
use Spatie\RouteAttributes\Attributes\Group;
#[Attribute(Attribute::TARGET_CLASS | Attribute::IS_REPEATABLE)]
class TeamGroup extends Group
{
public function __construct(
public ?string $prefix
) {
parent::__construct('team/{team:slug}/' . $prefix);
}
}

fix: use \ReflectionAttribute::IS_INSTANCEOF

---

README.md
src/Attributes/Resource.php
src/ClassRouteAttributes.php
src/RouteRegistrar.php
tests/AttributeTests/ResourceAttributeTest.php
tests/TestClasses/Controllers/Resource/ResourceTestNamesArrayController.php
tests/TestClasses/Controllers/Resource/ResourceTestNamesStringController.php

This allows you to specify the `names` parameter on the `Resource`.
If you had something like:
```php
#[Resource('posts', only: ['index', 'show'], names: 'api.v1.posts')]
class ResourceTestNamesStringController
{
public function index()
{
}
public function show($id)
{
}
}
```
You would get routes named:
`api.v1.posts.index`
`api.v1.posts.show`
You can also pass an array to the `names` parameter if you want to customize the route name for each controller action:
```php
#[Resource('posts', only: ['index', 'show'], names: ['index' => 'posts.list', 'show' => 'posts.view'])]
```
You would get routes named:
`posts.list`
`posts.view`

Add support for the names parameter to the Resource attribute

---

.github/workflows/run-tests.yml
composer.json
tests/AttributeTests/AnyAttributeTest.php
tests/AttributeTests/DeleteAttributeTest.php
tests/AttributeTests/Domain1AttributeTest.php
tests/AttributeTests/DomainAttributeTest.php
tests/AttributeTests/DomainFromConfigAttributeTest.php
tests/AttributeTests/GetAttributeTest.php
tests/AttributeTests/GroupAttributeTest.php
tests/AttributeTests/MiddlewareAttributeTest.php
tests/AttributeTests/OptionsAttributeTest.php
tests/AttributeTests/PatchAttributeTest.php
tests/AttributeTests/PostAttributeTest.php
tests/AttributeTests/PrefixAttributeTest.php
tests/AttributeTests/PutAttributeTest.php
tests/AttributeTests/ResourceAttributeTest.php
tests/AttributeTests/RouteAttributeTest.php
tests/AttributeTests/WhereAttributeTest.php
tests/Pest.php
tests/RouteDiscovery/DiscoverControllerTest.php
tests/RouteDiscovery/DiscoverViewsTest.php
tests/RouteDiscovery/RouteDiscoveryTest.php
tests/RouteRegistrarTest.php
tests/TestCase.php

This pull request contains changes for migrating your test suite from PHPUnit to [Pest](https://pestphp.com/) automated by the [Pest Converter](https://laravelshift.com/phpunit-to-pest-converter).
**Before merging**, you need to:
- Checkout the `shift-53383` branch
- Review **all** of the comments below for additional changes
- Run `composer update` to install Pest with your dependencies
- Run `vendor/bin/pest` to verify the conversion

PHPUnit to Pest Converter

---

README.md
src/RouteAttributesServiceProvider.php
tests/RouteRegistrarTest.php
tests/TestCase.php
tests/ThirdPartyTestClasses/Controllers/ThirdPartyController.php

As discussed #68 and #59 there is sometimes a need to define a path of controllers using a root namespace outside of the application's namespace.
By also supplying a root namespace with the directory path this can be achieved with, as it turns out, pretty small changes.
Details to consider, and perhaps discuss:
- In this case, the `RouteRegistrar::basePath` will always be the same as whatever directory you supply in the config (running `RouteRegistrar::registerDirectory()`). This makes me think that the base path property is redundant. I opted to not make any changes in the RouteRegistrar however, as it could be considered out of scope.
- Testing this is pretty ugly, as the test must load a class from outside the test namespace. I opted to manually require a "third party" controller in …

Namespaced controller directories

---

src/RouteRegistrar.php
tests/AttributeTests/ResourceAttributeTest.php
tests/TestCase.php

Hi @freekmurze 
This should fix #76. 
When registering a resource, it would only add middleware to the route when it would be explicitly defined, which meant that the default `SubstituteBindings` middleware was never being applied unless you also defined other middleware.
Also the check in the tests where an `array_diff` is done to make sure the middleware is present in the request was in the wrong order, resulting in always true.

Fixes implicit route model binding bug when using Resource attribute.

---

src/RouteRegistrar.php

Currently, the order of routes is not really predictable. Sorting them by controller's file names always guarantees the same order.

fix: make order of routes predictable

---

src/Attributes/Fallback.php
src/RouteRegistrar.php
tests/AttributeTests/FallbackAttributeTest.php
tests/TestCase.php
tests/TestClasses/Controllers/FallbackTestController.php

This PR adds a `Fallback` attribute that can be used to define fallback routes.

feat: add Fallback attribute

---

.github/workflows/run-tests.yml

Remove --ignore-platform-reqs from composer as this will cause dependencies with invalid php range to be installed (Eg: symfony/finder 6.1 on php8.0 which is only compatible with php8.1)

Fix automated tests

---

.github/workflows/run-tests.yml

The test are still failing because a package on windows requires fileinfo, this was the reason for the ignore-platform-reqs I believe

Add fileinfo extension

---

README.md
config/route-attributes.php
src/RouteAttributesServiceProvider.php
src/RouteRegistrar.php
tests/ServiceProviderTest.php
tests/TestCase.php
tests/TestClasses/Controllers/Grouped/GroupTestController.php

This PR adds the possibility to give group options by directory in the config, instead of having to add the group options at the top of each class
I had to refactor slighlty the TestCaseas I noticed that the ServiceProvider was instantiated in every test case but with the wrong config and not loading any route, and the tests were not using it at all
Now it is only instanced within the ServiceProviderTest with a set of configurable options

feat: add grouped configurations and improve tests

---

README.md
composer.json
src/Attributes/ScopeBindings.php
src/ClassRouteAttributes.php
src/RouteRegistrar.php
tests/AttributeTests/ScopeBindingsAttributeTest.php
tests/TestCase.php
tests/TestClasses/Controllers/BindingScoping1TestController.php
tests/TestClasses/Controllers/BindingScoping2TestController.php

This PR adds support for [scoped bindings](https://laravel.com/docs/9.x/routing#implicit-model-binding-scoping). It adds a new `ScopeBindings` attribute which may be used on controllers or controller methods.
Following the Laravel documentation, the following example...
```php
Route::get('/users/{user}/posts/{post}', function (User $user, Post $post) {
return $post;
})->scopeBindings();
```
...can now be implemented using route attributes as well:
```php
class PostsController
{
#[Get('/users/{user}/posts/{post}')]
#[ScopeBindings]
public function getUserPost(User $user, Post $post)
{
return $post;
}
}
```
As the attribute may be used on controllers, this also covers the grouped example case:
```php
Route::scopeBindings()->group(function () {
Route::get('/users/{user}/posts/{post}', …
```

Implemented scoped bindings

---

README.md
src/Attributes/ApiResource.php
src/ClassRouteAttributes.php
src/RouteRegistrar.php
tests/AttributeTests/ResourceAttributeTest.php
tests/TestClasses/Controllers/Resource/ApiResource1TestController.php
tests/TestClasses/Controllers/Resource/ApiResource2TestController.php
tests/TestClasses/Controllers/Resource/Resource1TestApiController.php
tests/TestClasses/Controllers/Resource/Resource2TestApiController.php
tests/TestClasses/Controllers/Resource/ResourceTestParametersController.php
tests/TestClasses/Controllers/Resource/ResourceTestShallowController.php

This pull request adds the support for two additional properties in `Spatie\RouteAttributes\Attributes\Resource` attribute class:
- `array|string|null $parameters`
- `bool|null $shallow`
Additionally, ApiResource attribute class was added just to make the Attribute declarations shorter when using named arguments.
```php
// Before
#[Resource('posts', shallow: true, apiResource: true)]
// After
#[ApiResource('posts', shallow: true)]
```
Tests for all additions are included.

Resource Attribute extended

---

README.md
src/Attributes/Defaults.php
src/ClassRouteAttributes.php
src/RouteRegistrar.php
tests/AttributeTests/DefaultAttributeTest.php
tests/TestCase.php
tests/TestClasses/Controllers/DefaultsTestController.php

First of all, thanks for this great package and great idea to generate routes from controller attributes. 
This PR allows you to add a `Defaults` annotation on a class or method to define the default values of your optional route parameters:
```php
use Spatie\RouteAttributes\Attributes\Defaults;
use Spatie\RouteAttributes\Attributes\Get;
use Spatie\RouteAttributes\Attributes\Post;
#[Defaults('param', 'controller-default')]
class MyController extends Controller
{
#[Get('my-get-route/{param?}')]
public function myGetMethod($param)
{
}
#[Post('my-post-route/{param?}/{param2?}')]
#[Defaults('param2', 'method-default')]
public function myPostMethod($param, $param2)
{
}
#[Get('my-default-route/{param?}/{param2?}/{param3?}')]
#[Defaults('param2', 'method-default-first')]
#[Defaults('param3', …
```

Add defaults as attribute

---

README.md
src/Attributes/WhereUlid.php
tests/AttributeTests/WhereAttributeTest.php
tests/TestClasses/Controllers/WhereTestController.php

This PR adds a new shorthand where attribute to handle ULIDs.
Support for ULIDs were introduced in Laravel 9.30.1 as an alternative for Eloquent models primary keys.
Notes:
- As per ULID spec:
- all characters should be compatible with Crokford's base32 (digits and letters other than `I`, `L`, `O`, and `U`)
- also, the largest ULID to be allowed is `7ZZZZZZZZZZZZZZZZZZZZZZZZZ` 
- therefore, the first character must be in the range `[0-7]`
- while all remaining 25 characters should be in range `[0-9A-HJKMNP-TV-Z]`
- this justifies the regular expression used
- A relevant test case was adapted to check for this new attribute.
References:
- https://github.com/laravel/framework/blob/9.x/CHANGELOG.md#v9301---2022-09-15
- https://github.com/ulid/spec
- https://www.crockford.com/base32.html

Add WhereUlid shorthand where

---

.github/workflows/run-tests.yml
composer.json

This PR adds PHP 8.2 to the tests workflow and bumps the version of the `checkout` action to v3. It also bumps some minimum dependency versions and adds additional configuration to the tests workflow to allow PHP 8.2 support.

Add PHP 8.2 to tests workflow

---

src/ClassRouteAttributes.php

Given the ff config:
```php
return [
...
'directories' => [
app_path('HttpApi/Controllers') => [
'domain' => parse_url(env('APP_URL', ''), PHP_URL_HOST),
],
],
...
],
```
Prior to this PR, it tries to register the ff and causes an error:
```
"domain" => [
'localhost',
null,
]
```
The proposed solution filters null option in the group.

🐛 Should filter null values when resolving group

---

README.md
config/route-attributes.php
src/RouteAttributesServiceProvider.php
src/RouteRegistrar.php
tests/RouteRegistrarTest.php

I am using a modular directory structure where I co-locate my controllers, form requests, and even tests in the same directory. I ran into a problem when it was scanning files to look for route attributes it loaded one of my test files but since in production I run composer with `--no-dev` it did not have the `PHPUnit\Framework\TestCase` and I got a class not found error. I needed a way to be more specific with which files are checked for routes.
In your `config/route-attributes.php` file if you are using the array format then you can specify `patterns` and `not_patterns` for that directory.
```php
'directories' => [
app_path('Http/Controllers/Api') => [
'prefix' => 'api',
'middleware' => 'api',
// only register routes in files that match the patterns
'patterns' => ['*Controller.php'],
// …
```

Add patterns and not_patterns options to directories

---

src/Attributes/Delete.php
src/Attributes/Get.php
src/Attributes/Options.php
src/Attributes/Patch.php
src/Attributes/Post.php
src/Attributes/Put.php
tests/AttributeTests/DeleteAttributeTest.php
tests/AttributeTests/GetAttributeTest.php
tests/AttributeTests/OptionsAttributeTest.php
tests/AttributeTests/PatchAttributeTest.php
tests/AttributeTests/PostAttributeTest.php
tests/AttributeTests/PutAttributeTest.php
tests/TestClasses/Controllers/DeleteMultipleTestController.php
tests/TestClasses/Controllers/GetMultipleTestController.php
tests/TestClasses/Controllers/OptionsMultipleTestController.php
tests/TestClasses/Controllers/PatchMultipleTestController.php
tests/TestClasses/Controllers/PostMultipleTestController.php
tests/TestClasses/Controllers/PutMultipleTestController.php

Makes the `#[Get('')]` Attribute repeatable and therefore allows multiple `Get` route declarations to be added to a single method. Like this:
```
#[Get('my-get-method')]
#[Get('my-other-get-method')]
public function myMethod() {}
```
Im not sure what implications this might have, but it would definitely be handy from time to time - at least for me :-)
If you are interested, I could expand this PR to the other verbs / attributes.

Allow to register multiple Get route declarations on one method

---

README.md
src/Attributes/WithTrashed.php
src/ClassRouteAttributes.php
src/RouteRegistrar.php
tests/AttributeTests/WithTrashedAttributeTest.php
tests/TestCase.php
tests/TestClasses/Controllers/WithTrashedTestController.php

Added WithTrashed attribute to correspond to the withTrashed method on route registration

Added WithTrashed attribute 

---

src/Attributes/Any.php
src/Attributes/Route.php

Follow up of https://github.com/spatie/laravel-route-attributes/pull/132 https://github.com/spatie/laravel-route-attributes/commit/26e7bbf1e93345e962918501f3373109abed1452
It seems a few attributes where missed
Route is especially important, because it could be used to define the same path with different methods and different middlewares

Make Route and Any repeatable attributes

---

src/Attributes/Any.php
src/Attributes/Delete.php
src/Attributes/Get.php
src/Attributes/Patch.php
src/Attributes/Post.php
src/Attributes/Put.php
src/Attributes/Route.php
src/RouteRegistrar.php
tests/AttributeTests/FallbackAttributeTest.php
tests/AttributeTests/WithoutMiddlewareAttributeTest.php
tests/TestCase.php
tests/TestClasses/Controllers/WithoutMiddlewareTestController.php
tests/TestClasses/Middleware/SkippedMiddleware.php

Added missing option to define a `withoutMiddleware` when defining single route.
Also have changed [FallbackAttributeTest.php](https://github.com/spatie/laravel-route-attributes/compare/main...mikield:laravel-route-attributes:main?expand=1#diff-dc079cffa691d8a9e5372f3c5ee5ccaef15b9ceb2d9699a69560fb7f64f81326) to use named arguments when calling assertion, to avoid parameters mismatch error.

Add WithoutMiddleware option to route

---

src/RouteAttributesServiceProvider.php

It helps with tweaking `RouteRegistrar` in the case of an unorthodox directory structure
My use case for tweaking `RouteRegistrar`  was changing it like this:
```php
public function useBasePath(string $basePath): self {
// Wrapped in realpath()
$this->basePath = realpath(str_replace(['/', '\\'], DIRECTORY_SEPARATOR, $basePath));
return $this;
}
```
which allows using `..` in directory names, but it also resolves symlinks, so I don't suggest this change as another PR to fix the underlying problem, as a proper fix would be quite verbose and I don't really care to commit to this further, but I would be happy if it was incorporated in the library as well.

Create RouteRegistrar with DI instead of literal instantiation
